[project]
name = "fun-asr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "compute-wer>=0.2.3",
    "funasr>=1.3.0",
    "pyopenjtalk-plus>=0.4.1.post7",
    "torch>=2.9.1",
    "torchaudio>=2.9.1",
    "transformers>=4.57.6",
    "whisper-normalizer>=0.1.12",
    "zhconv>=1.4.3",
]


# 官方 PyPI 镜像（默认国内源可选）
[[tool.uv.index]]
name = "internal-proxy"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[[tool.uv.index]]
name = "huawei"
url = "https://mirrors.huaweicloud.com/repository/pypi/simple"
